### ISSUE TITLE
ENR incompatibility

### ISSUE THREAD

**Issue by holiman** [rust-ethereum/enr#18]
This is an enr record taken from https://github.com/ethereum/discv4-dns-lists/blob/master/all.ropsten.ethdisco.net/nodes.json#L20. 

The `devp2p  enrdump` of that record: 

```
 ./devp2p enrdump "enr:-Je4QDa1FydMysP1D_SCU40y6oJzJx3tcypUm27jGo1sAsl5aHdBD7179oxSwU2toRZD_EN80FIN4UPeNN3MD2SwzlRUg2V0aMfGhGcn75CAgmlkgnY0gmlwhMPJwBeJc2VjcDI1NmsxoQMGqA6CChLPbypJEPUGlZBCgt3b0pkTjMwjAAGDFkfOmoN0Y3CCdmGDdWRwgnZh"
Node ID: 0168ab071ed27549c208d36816234a4552722ac2395e1bbffbe94ba12f63604e
URLv4:   enode://06a80e820a12cf6f2a4910f50695904282dddbd299138ccc230001831647ce9a2b5197307941232bc946c5db4df0823da7ceeda98327fb2fa1a34a0cd1ed7e6b@195.201.192.23:30305
Record has sequence number 84 and 6 key/value pairs.
  "eth"       c7c6846727ef9080
  "id"        "v4"
  "ip"        195.201.192.23
  "secp256k1" a10306a80e820a12cf6f2a4910f50695904282dddbd299138ccc230001831647ce9a
  "tcp"       30305
  "udp"       30305
```

@vorot93 tells me that it fails on this library. Let's use this ticket to track down the incompatibility. 
cc @fjl

**Comment by AgeManning** [comment]
Yep. There was an incompatibility in how recursive rlp data was being stored in our ENR. 

This should be corrected in https://github.com/rust-ethereum/enr/pull/17

**Comment by vorot93** [comment]
Should be fixed now.

**Comment by holiman** [comment]
Could you expand a bit on the effects of this? Like, does it affect DNS-discovery only, or p2p handshake in general? Does it affect OE 3.x.x? Does it affect Parity 2.5.13?

**Comment by AgeManning** [comment]
I'm not sure the extent of this ENR crate used in eth1. 

It was originally built for discv5. The major issue with previous versions was that we were not verifying the ENR signature. Thus node records could be signed by anyone and treated as valid. 

In Discv5, Enrs are stored in the local routing table and propagated amongst peers. The discv5 handshake is somewhat independent of the ENR signature. If there were ENR's in a discovery implementation with invalid signatures. This library would treat them as valid and send them to other nodes. Other implementations would likely just reject the ENR (due to the invalid signature). The discv5 handshake involves updating the ENR's of negotiating nodes. It's unlikely a local implementation will create an invalid signature, so the ENR should be fine and the handshakes should be fine. I'm not sure of the extent that discv5 is used in eth1 in the rust language (but I understand its quite limited). 

The second element to this issue was how we are decoding and storing ENR values that are RLP lists. In Eth2 we have no ENR records whose value is an RLP list. Geth seems to produce a field "eth1" which stores RLP list values. Versions prior to this fix, would decode this value incorrectly. The result would be that reading the "eth1" field of a decoded ENR would not match that expected by geth or another implementation. So this field and any others (using RLP lists as values) would not be correctly decoded. I imagine that if an implementation was using this field, this error would have been very obvious as the field would not make sense. 

The fact that this has only been raised indirectly would lead me to believe that there is no implementation using this ENR crate to decode the "eth1" field (or any field that has an RLP list value) currently.
